const marketplaceImage="assets/marketplace-visual.svg";
const categories=["Tum urunler","Ev","Taki","Giyim","Sanat","Gurme"];
const shops=[{name:"Atolye Mira",text:"Dokuma, kumas ve ev aksesuarlariyla sicak bir vitrin.",products:126,followers:"12K"},{name:"Kil & Sirdan",text:"Seramik kupalar, tabaklar ve ufak seri sofra urunleri.",products:84,followers:"8K"},{name:"Luna Taki",text:"Gumus, dogal tas ve renkli minimal taki tasarimlari.",products:211,followers:"19K"}];
const products=[
{id:1,name:"El dokumasi renkli runner",shop:"Atolye Mira",category:"Ev",price:890,rating:4.9,date:8,tag:"Yeni",imagePosition:"24% 42%"},
{id:2,name:"Mercan sirlama seramik fincan",shop:"Kil & Sirdan",category:"Ev",price:420,rating:4.8,date:4,tag:"Cok satan",imagePosition:"52% 44%"},
{id:3,name:"Dogal tas gumus kolye",shop:"Luna Taki",category:"Taki",price:1260,rating:5,date:7,tag:"Favori",imagePosition:"73% 38%"},
{id:4,name:"Organik pamuk yazlik kimono",shop:"Yavas Moda",category:"Giyim",price:1680,rating:4.7,date:2,tag:"Vitrin",imagePosition:"34% 72%"},
{id:5,name:"Limitli baski poster seti",shop:"Cizgi Ev",category:"Sanat",price:540,rating:4.6,date:9,tag:"Sanat",imagePosition:"82% 66%"},
{id:6,name:"Tas degirmen fistik ezmesi",shop:"Kavanoz",category:"Gurme",price:310,rating:4.9,date:1,tag:"Taze",imagePosition:"58% 76%"},
{id:7,name:"Kece laptop kilifi",shop:"Atolye Kuzey",category:"Giyim",price:740,rating:4.5,date:6,tag:"Pratik",imagePosition:"18% 70%"},
{id:8,name:"El boyamasi dekoratif kase",shop:"Kil & Sirdan",category:"Sanat",price:980,rating:4.8,date:3,tag:"El yapimi",imagePosition:"46% 28%"},
{id:9,name:"Renkli boncuk bileklik seti",shop:"Luna Taki",category:"Taki",price:360,rating:4.7,date:5,tag:"Hediye",imagePosition:"76% 22%"}
];
const state={category:"Tum urunler",query:"",sort:"featured",cart:[],spotlightIndex:0};
const $=s=>document.querySelector(s);
const productGrid=$("#productGrid"),categoryTabs=$("#categoryTabs"),searchInput=$("#searchInput"),sortSelect=$("#sortSelect"),cartPanel=$("#cartPanel"),cartButton=$("#cartButton"),closeCart=$("#closeCart"),scrim=$("#scrim"),cartItems=$("#cartItems"),cartCount=$("#cartCount"),cartTotal=$("#cartTotal"),shopStrip=$("#shopStrip"),spotlightShop=$("#spotlightShop"),spotlightText=$("#spotlightText"),shuffleSpotlight=$("#shuffleSpotlight"),dealTicker=$("#dealTicker"),sellerForm=$(".seller-form"),sellerStatus=$("#sellerStatus");
const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0});
function getVisibleProducts(){const q=state.query.trim().toLocaleLowerCase("tr-TR");return products.filter(p=>{const ok=state.category==="Tum urunler"||p.category===state.category;const hay=`${p.name} ${p.shop} ${p.category}`.toLocaleLowerCase("tr-TR");return ok&&hay.includes(q)}).sort((a,b)=>{if(state.sort==="newest")return a.date-b.date;if(state.sort==="priceLow")return a.price-b.price;if(state.sort==="priceHigh")return b.price-a.price;if(state.sort==="rating")return b.rating-a.rating;return b.rating*100-b.price/100-(a.rating*100-a.price/100)})}
function renderCategories(){categoryTabs.innerHTML=categories.map(c=>`<button class="tab ${c===state.category?"active":""}" type="button" data-category="${c}">${c}</button>`).join("")}
function renderProducts(){const visible=getVisibleProducts();if(!visible.length){productGrid.innerHTML=`<p class="empty-state">Bu aramada urun bulunamadi. Baska bir kategori dene.</p>`;return}productGrid.innerHTML=visible.map((p,i)=>`<article class="product-card" style="animation-delay:${i*45}ms"><div class="product-image"><img src="${marketplaceImage}" alt="${p.name}" style="object-position:${p.imagePosition}"/><span class="badge">${p.tag}</span></div><div class="product-info"><div class="product-meta"><span>${p.shop}</span><span>${p.category}</span></div><h3>${p.name}</h3><span class="rating">Puan ${p.rating.toFixed(1)}</span><div class="product-bottom"><span class="price">${money.format(p.price)}</span><button class="add-button" type="button" data-id="${p.id}">+</button></div></div></article>`).join("")}
function renderShops(){shopStrip.innerHTML=shops.map(s=>`<article class="shop-card"><img src="${marketplaceImage}" alt="${s.name} magazasi icin urun vitrini"/><div class="shop-card-body"><h3>${s.name}</h3><p>${s.text}</p><div class="shop-meta"><span>${s.products} urun</span><span>${s.followers} takipci</span></div></div></article>`).join("")}
function renderSpotlight(){const s=shops[state.spotlightIndex];spotlightShop.textContent=s.name;spotlightText.textContent=s.text}
function renderCart(){cartCount.textContent=state.cart.length;cartTotal.textContent=money.format(state.cart.reduce((sum,item)=>sum+item.price,0));if(!state.cart.length){cartItems.innerHTML=`<p class="empty-state">Sepetin henuz bos. Vitrinden bir urun ekleyebilirsin.</p>`;return}cartItems.innerHTML=state.cart.map(item=>`<div class="cart-row"><img src="${marketplaceImage}" alt="${item.name}"/><div><h3>${item.name}</h3><span>${item.shop}</span></div><strong>${money.format(item.price)}</strong></div>`).join("")}
function openCart(){cartPanel.classList.add("open");scrim.classList.add("open")}function closeCartPanel(){cartPanel.classList.remove("open");scrim.classList.remove("open")}
function animateCounters(){document.querySelectorAll("[data-count-to]").forEach(counter=>{const target=Number(counter.dataset.countTo),step=Math.max(1,Math.round(target/42));let value=0;const timer=setInterval(()=>{value=Math.min(target,value+step);counter.textContent=target>=1000?value.toLocaleString("tr-TR"):value;if(value>=target)clearInterval(timer)},32)})}
function startDealTicker(){let seconds=720;setInterval(()=>{seconds=seconds>0?seconds-1:720;const m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");dealTicker.textContent=`${m}:${s}`},1000)}
categoryTabs.addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;state.category=b.dataset.category;renderCategories();renderProducts()});
productGrid.addEventListener("click",e=>{const b=e.target.closest("[data-id]");if(!b)return;state.cart.push(products.find(p=>p.id===Number(b.dataset.id)));renderCart();openCart()});
searchInput.addEventListener("input",e=>{state.query=e.target.value;renderProducts()});sortSelect.addEventListener("change",e=>{state.sort=e.target.value;renderProducts()});shuffleSpotlight.addEventListener("click",()=>{state.spotlightIndex=(state.spotlightIndex+1)%shops.length;renderSpotlight()});cartButton.addEventListener("click",openCart);closeCart.addEventListener("click",closeCartPanel);scrim.addEventListener("click",closeCartPanel);
sellerForm.addEventListener("submit",e=>{e.preventDefault();const data=new FormData(sellerForm);sellerStatus.textContent=`${data.get("shopName")} icin basvuru taslagi hazir. Sonraki adimda satici panelini kuracagiz.`;sellerForm.reset()});
renderCategories();renderProducts();renderShops();renderSpotlight();renderCart();animateCounters();startDealTicker();
